// SPDX-License-Identifier: 0BSD
pragma solidity ^0.8.20;
// GENERATED by web/porw-browser/export_fixtures.mjs — the browser node's signed residency claim.
library BrowserClaimFixture {
    bytes32 constant SCHEME_DIGEST = 0x48bbcf993c40ccbab6c43697518f5ebe860e8ef282390f3519bfd5c212111726; bytes32 constant MEP_ID = 0x580ae348fa8d127fa04811abfdebc0109fa0b8596cad5d1aaa3ffb04b5c474ec; bytes32 constant MODEL_ID = 0xa370545be2f09b79e3b9a0fe4e96a03a7a75ad1c2521f03ae63438cf2754411d;
    bytes32 constant EXEC_KIND = 0xddaf2a689a2584c585650d196bb1e58103b5b610cf8b087c1cc2ca3c67afb6fc; uint32 constant NEURONS = 4000; uint32 constant SYNAPSES = 40000; bytes32 constant SYNAPSE_ROOT = 0x0637d357a1cd9d4d2cc36c42dd8c5ba9179163eb0281c9e6ae784f05b8a2a373;
    bytes32 constant PARTIALS_ROOT = 0x6730223e1bfd1a417709b9d6a998b6e6821e141b30c27fc6eb20f35ddd926381; uint64 constant COVERAGE_BYTES = 434176; bytes32 constant CHALLENGE = 0xd4a737ae2000efaa0f98972affcea9dfa34703d5deed2348f48dc16bc2160a60;
    bytes32 constant CLAIM_HASH = 0x50341b0af6dc612fc88bc934adb1fda7cdddfbe23ead3bc2c044e48f8c1efafe; bytes32 constant CLAIM_DIGEST = 0x6ff3c15fd7045703b8c2d370a99264dd3a5c8338ae71a446a99f73fc0a4c3bb2; address constant SIGNER = 0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A; address constant INSTANCE = 0xef4B70013a5D27da61D71ad716fe1294F748D152;
    uint256 constant CHAIN_ID = 31337; address constant CLAIM_MANAGER = 0x000000000000000000000000000000000000C1a1; address constant REGISTRY = 0x0000000000000000000000000000000000005e61;
    function signature() internal pure returns (bytes memory) { return hex"8a38fb7a23e4c47e7bd84bd5472a9c5faa6e981ddd5792b79f818319deda38a836fb021c2040210cfb9ced4e3289a6b56beb40456a67f0edb40970fad705f5b71c"; }
    function delegation() internal pure returns (address instance, address session, uint64 expiry, bytes memory sig) { instance = 0xef4B70013a5D27da61D71ad716fe1294F748D152; session = 0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A; expiry = 100000; sig = hex"fade0474a5f9543ece81850e8d883613dc6a1f2fc7a05a591ed1cddf15469f1d2212520cac01b3d16bf2ad70343adb86728d08965c97dcf3826358ea9711beb41c"; }
}
