// SPDX-License-Identifier: 0BSD
pragma solidity ^0.8.20;
// GENERATED by web/porw-browser/export_fixtures.mjs — the browser node's signed residency claim.
library BrowserClaimFixture {
    bytes32 constant SCHEME_DIGEST = 0x718b2eb3b33a6d18d904363ee1cc2fb797e344af10132ebfd93aef8d5d72e4b4; bytes32 constant MEP_ID = 0xc98e0ec371e4b9930ce9156da334ab3304e9da070999afdb5b00ca6b18215c11; bytes32 constant MODEL_ID = 0xa370545be2f09b79e3b9a0fe4e96a03a7a75ad1c2521f03ae63438cf2754411d;
    bytes32 constant EXEC_KIND = 0xddaf2a689a2584c585650d196bb1e58103b5b610cf8b087c1cc2ca3c67afb6fc; uint32 constant STEPS = 2; uint32 constant CLAMP_Q16 = 65536;
    bytes32 constant PARTIALS_ROOT = 0x2d215117f2bfdb48020c1eba8d1d726edf05ba201dbbbb365fcd5afafdbecebe; uint64 constant COVERAGE_BYTES = 434176; bytes32 constant CHALLENGE = 0x14e56b93716199c063471b642fd434c575b4525db3702e419718452cc046b1a1;
    bytes32 constant DEVICE_ID = 0x8dd832049319556c1cd22ed66ae790d07fea25830a6151c2f0a9879b3ef61305; bytes32 constant EXEC_DIGEST = 0xd6ee81311837ea63a73424ce66d9d165665bc7e7d8a70f35c9d84f337e1fac05; uint32 constant STIMULUS_SEED = 5;
    bytes32 constant CLAIM_HASH = 0xe26306625483cb49eb403b5a60e8624e4b293a8e8eba885420af5f5c0155690b; bytes32 constant CLAIM_DIGEST = 0x4beb67f812c1850980fb84c26767a6c2c4f77312f40a8833444da13d1d8b389c; address constant SIGNER = 0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A; address constant INSTANCE = 0xef4B70013a5D27da61D71ad716fe1294F748D152;
    uint256 constant CHAIN_ID = 31337; address constant CLAIM_MANAGER = 0x000000000000000000000000000000000000C1a1; address constant REGISTRY = 0x0000000000000000000000000000000000005e61;
    function signature() internal pure returns (bytes memory) { return hex"732541bb58e976ec83bd8a067cab226ff2c2332b44f9cbf1a7d0fe6d4fe6b82d318189518a0fc1aed05d38c703d86cc1c183fd86b55680bfe77047a20bfc5a0f1c"; }
    function delegation() internal pure returns (address instance, address session, uint64 expiry, bytes memory sig) { instance = 0xef4B70013a5D27da61D71ad716fe1294F748D152; session = 0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A; expiry = 100000; sig = hex"fade0474a5f9543ece81850e8d883613dc6a1f2fc7a05a591ed1cddf15469f1d2212520cac01b3d16bf2ad70343adb86728d08965c97dcf3826358ea9711beb41c"; }
}
