// SPDX-License-Identifier: 0BSD
pragma solidity ^0.8.20;
// GENERATED by web/porw-browser/export_fixtures.mjs — the browser node's signed residency claim.
library BrowserClaimFixture {
    bytes32 constant SCHEME_DIGEST = 0x743502825425e31852a0adb96c797d7ac839afdef315e8c24b68db6e58d4be2e; bytes32 constant MEP_ID = 0x3fa10d992b85f5e8bc379d4f626010716e357d4c85de81176db1c71074b37e06; bytes32 constant MODEL_ID = 0xa370545be2f09b79e3b9a0fe4e96a03a7a75ad1c2521f03ae63438cf2754411d;
    bytes32 constant EXEC_KIND = 0xddaf2a689a2584c585650d196bb1e58103b5b610cf8b087c1cc2ca3c67afb6fc; uint32 constant NEURONS = 4000; uint32 constant SYNAPSES = 40000; bytes32 constant SYNAPSE_ROOT = 0x0637d357a1cd9d4d2cc36c42dd8c5ba9179163eb0281c9e6ae784f05b8a2a373;
    bytes32 constant PARTIALS_ROOT = 0x869408b16ed0c67951eeeb0ac5d151c4f49fbd15dafebd3faf8a90e94dae365a; uint64 constant COVERAGE_BYTES = 434176; bytes32 constant CHALLENGE = 0x14f25d0c516dcec37726a0f15b2af557a05f897e35fce64e737f952bd0653462;
    bytes32 constant CLAIM_HASH = 0xeb1b46320793406fb7dd8d308b175fbf8b7e9fa50c0aeb9a632b85d958308c2f; bytes32 constant CLAIM_DIGEST = 0xa43841dc2a6922f7f9506ef73f5e188dd602ad57e21614cf772a3be92e088a0d; address constant SIGNER = 0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A; address constant INSTANCE = 0xef4B70013a5D27da61D71ad716fe1294F748D152;
    uint256 constant CHAIN_ID = 31337; address constant CLAIM_MANAGER = 0x000000000000000000000000000000000000C1a1; address constant REGISTRY = 0x0000000000000000000000000000000000005e61;
    function signature() internal pure returns (bytes memory) { return hex"4114862c79712c758d9dc99dae7f544a3c7c713d9a80209ae4e4440bdb30fd171db5f6e0923af09dbc5e11282882103e205f82f4f66595d4dca5919d9ef2d19f1c"; }
    function delegation() internal pure returns (address instance, address session, uint64 expiry, bytes memory sig) { instance = 0xef4B70013a5D27da61D71ad716fe1294F748D152; session = 0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A; expiry = 100000; sig = hex"fade0474a5f9543ece81850e8d883613dc6a1f2fc7a05a591ed1cddf15469f1d2212520cac01b3d16bf2ad70343adb86728d08965c97dcf3826358ea9711beb41c"; }
}
