// SPDX-License-Identifier: 0BSD
pragma solidity ^0.8.20;
// GENERATED by web/porw-browser/test_lif.mjs from a real node run (synthetic v2 brain) — do not edit.
import "../../src/mesh/LifRowCheck.sol";

library LifVectors {
    bytes32 constant EXEC_KIND = 0x0c387b3972c70c927c1f37f69ba2b8183ab1d666641f4aa33f46e6cbeda888d9;
    uint32 constant N = 10;
    struct Vec { uint32 i; uint32 step; uint32 seed; int64 I; LifRowCheck.State before; LifRowCheck.State after_; bytes32 leafAfter; string kind; }
    function get(uint32 j) internal pure returns (Vec memory v) {
        if (j == 0) return Vec(0, 21, 3, 0, LifRowCheck.State(0, 0, 0, 1, 1), LifRowCheck.State(0, 0, 0, 1, 1), 0xeb2019d71598a0ee999b52d787f0e62ff71dea9ff6e5671b01b0898005ef848a, "stim");
        if (j == 1) return Vec(1, 21, 3, 24, LifRowCheck.State(0, 0, 0, 0, 0), LifRowCheck.State(2164, 432528, 0, 0, 0), 0x9b30023262dd12e158efa0da67cf1d89825ec749bcd0aa4c63949adb9827be49, "sub");
        if (j == 2) return Vec(7, 21, 3, 26, LifRowCheck.State(0, 0, 0, 0, 0), LifRowCheck.State(2345, 468572, 0, 0, 0), 0x3480b49bd31bfdc08e6abab5990721b2dce2aadac33a6d7ef7d2969d3b90182b, "sub");
        if (j == 3) return Vec(11, 21, 3, 0, LifRowCheck.State(0, 388338, 0, 1, 1), LifRowCheck.State(0, 380570, 0, 1, 1), 0xf696ca704acfdae89f87b9ccd3738b25352794090be773660c89ce1ebad14fbc, "stim");
        if (j == 4) return Vec(27, 24, 3, -49, LifRowCheck.State(-67162, -613801, 0, 0, 0), LifRowCheck.State(-74257, -1484600, 0, 0, 0), 0xfac32e01433e2c0c7f97d7b20bc7fece7e9d80fcc74945d986249296a32a6a1c, "neg");
        if (j == 5) return Vec(54, 24, 3, -9, LifRowCheck.State(4293, 167034, 0, 0, 0), LifRowCheck.State(4278, 1495, 0, 0, 0), 0xf401e0fdc38fe46d629c56398d17aac8931b3589260a9891fc1d1e0286f37574, "neg");
        if (j == 6) return Vec(2689, 39, 3, 0, LifRowCheck.State(0, 2253912, 21, 0, 1), LifRowCheck.State(0, 2208825, 20, 0, 1), 0xed739b530e32cf16bef9aaa5b0d419ac366dabb3203277c15a0827fddaa86355, "refr");
        if (j == 7) return Vec(2689, 42, 3, 0, LifRowCheck.State(0, 2121338, 18, 0, 1), LifRowCheck.State(0, 2078903, 17, 0, 1), 0x4dfd3f3b776e68d3d12fa0919de78abd85ae9fc74410e05e2b193c248757569b, "refr");
        if (j == 8) return Vec(4888, 48, 3, 0, LifRowCheck.State(453227, 2757616, 0, 0, 0), LifRowCheck.State(0, 2702452, 22, 2, 1), 0x87ed827439a58c4ea95956771b43f7ff77d5f0935f96c4ccfd480db49d93b533, "spike");
        if (j == 9) return Vec(284, 51, 3, 57, LifRowCheck.State(450213, 1334245, 0, 0, 0), LifRowCheck.State(0, 2334809, 22, 2, 1), 0x99d66b83f6c3ca7932f276d3b3a872c1b3f08cec1b1a16d9f3c34ee85236c081, "spike");
        revert("vec");
    }
}
