import fs from "node:fs";
import { loadKernelFromBytes } from "./porw.js";
import { decodeHeader, attachSpmv } from "./model.js";
import { blake3 } from "@noble/hashes/blake3.js";
const base = process.argv[2];
const exp = JSON.parse(fs.readFileSync(base + ".json", "utf8"));
const payload = new Uint8Array(fs.readFileSync(base + ".bin"));
const k = attachSpmv(await loadKernelFromBytes(fs.readFileSync(new URL("./sketch.wasm", import.meta.url))), null);
attachSpmv(k, k.exports);
const bufPtr = k.put(payload);
const hdr = decodeHeader(payload);
const act = k.spmvStimulus(hdr.neurons, exp.seed);
const t0 = performance.now(); k.spmvRun(bufPtr, hdr, act, exp.steps); const ms = performance.now() - t0;
const out = k.u32(act, hdr.neurons);
const bytes = new Uint8Array(out.buffer, out.byteOffset, out.byteLength);
const dig = "0x" + Buffer.from(blake3(bytes)).toString("hex");
const nonzero = out.reduce((s, v) => s + (v > 0 ? 1 : 0), 0), sum = out.reduce((s, v) => s + v, 0);
console.log(`wasm spmv: ${hdr.neurons} neurons, ${hdr.synapses} synapses x ${exp.steps} steps in ${ms.toFixed(1)} ms; nonzero ${nonzero} sum ${sum}`);
console.log("head wasm  :", Array.from(out.subarray(0, 8)).join(","));
console.log("head python:", exp.act_head.join(","));
const ok = dig === exp.act_blake3 && nonzero === exp.act_nonzero && sum === exp.act_sum;
console.log(ok ? "BIT-EXACT vs python int64 reference: true" : `MISMATCH: ${dig} vs ${exp.act_blake3}`);
process.exit(ok ? 0 : 1);
